name: NER Train
id: 35ff6570-c9af-4304-a57a-2b63ba216396
version: 0.0.7.0
category: Machine Learning\Train
description: NER train module.
owner: Jincheng Chen
inputs:
- name: Input train data
  type: DataFrameDirectory
  port: True
  description: input train data
- name: Bert pretrained model
  type: Mode
  default: "bert-base-cased"
  description: Specify BERT pretrained model
  options:
    - bert-base-uncased
    - bert-base-cased
    - bert-large-uncased
    - bert-large-cased
- name: Maximum sequence length
  type: Int
  default: 128
  description: Specify maximum sequence length
- name: Number of training epochs
  type: Int
  default: 5
  description: Specify number of training epochs
    training
- name: Warmup proportion
  type: Float
  default: 0.4
  description: Specify warmup proportion
outputs:
- name: Output model
  type: ModelDirectory
  description: The output directory where the model predictions and checkpoints will be written.
implementation:
  container:
    runConfig:
      baseDockerImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      gpuSupport: True
    conda:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.6.2
      - pip:
        - --extra-index-url=https://test.pypi.org/simple
        - https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
        - regex==2019.11.1
        - pytorch-pretrained-bert==0.6.1
        - seqeval==0.0.5
        - tqdm==4.31.1
        - nltk==3.4
        - torchvision==0.3.0
        - pandas==0.24.1
        - pyarrow==0.12.1
        - git+https://github.com/weedqian/CustomModules-1.git@weda/ner-demo#subdirectory=azureml-custom-module-examples/ner-bert
    command:
    - python
    - -m
    - script.train
    args:
    - --train-feature-dir
    - inputValue: Input train data
    - --bert-model
    - inputValue: Bert pretrained model
    - --max-seq-length
    - inputValue: Maximum sequence length
    - --num-train-epochs
    - inputValue: Number of training epochs
    - --warmup-proportion
    - inputValue: Warmup proportion
    - --output-model-dir
    - outputPath: Output model
