amlModuleIdentifier:
  moduleName: Deeplabv3 Train
  moduleVersion: 0.0.9
  namespace: microsoft.com/azureml/samples
metadata:
  annotations:
    tags:
    - Machine Learning\Train
description: Creates a Deeplabv3 for semantic segmentation and trains it
inputs:
- name: Model type
  type: Mode
  default: deeplabv3_resnet101
  description: model_type
  options:
  - deeplabv3_resnet101
  - fcn_resnet101
- name: Model path
  type: ModelDirectory
  description: model_path
- name: Data path
  type: AnyDirectory
  description: data_path
- name: Pretrained
  type: Boolean
  default: true
  description: pretrained
- name: Learning rate
  type: Float
  default: 0.0001
  description: learning_rate
- name: Epochs
  type: Int
  default: 10
  description: epochs
- name: Batch size
  type: Int
  default: 4
  description: batch_size
- name: Use CUDA
  type: Boolean
  default: false
  description: use_cuda
outputs:
- name: Save path
  type: ModelDirectory
  description: save_path
implementation:
  container:
    amlEnvironment:
      docker:
        baseImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      python:
        condaDependencies:
          name: project_environment
          channels:
          - defaults
          dependencies:
          - python=3.6.3
          - py-opencv=3.4.2
          - pip:
            - azureml-core==1.0.72
            - azureml-dataprep[fuse,pandas]==1.3.5
            - fire==0.1.3
            - torch==1.3
            - torchvision==0.4.1
    command: [python, ssdeeplabv3/train.py]
    args: [
      --model_type, {inputValue: Model type},
      --model_path, {inputPath: Model path},
      --data_path, {inputPath: Data path},
      --pretrained, {inputValue: Pretrained},
      --learning_rate, {inputValue: Learning rate},
      --epochs, {inputValue: Epochs},
      --batch_size, {inputValue: Batch size},
      --use_cuda, {inputValue: Use CUDA},
      --save_path, {outputPath: Save path},
    ]
