amlModuleIdentifier:
  moduleName: Stargan Train
  moduleVersion: 0.0.2
  namespace: microsoft.com/azureml/samples
metadata:
  annotations:
    tags:
    - Machine Learning\Train
description: Creates a stargan train module
inputs:
- name: Dataset type
  type: Mode
  default: RaFD
  description: dataset_type
  options:
  - RaFD
  - CelebA
- name: Train data path
  type: AnyDirectory
  description: train_data_path
- name: Evaluate data path
  type: AnyDirectory
  description: evaluate_data_path
- name: Image size
  type: Int
  default: 128
  description: image_size
- name: Label dim
  type: Int
  default: 5
  description: dimension of domain labels
- name: Number of iterations
  type: Int
  default: 10000
  description: the number of iterations
- name: Batch size
  type: Int
  default: 16
  description: batch_size
outputs:
- name: Save path
  type: ModelDirectory
  description: save_path
implementation:
  container:
    amlEnvironment:
      docker:
        baseImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      python:
        condaDependencies:
          name: project_environment
          channels:
          - defaults
          dependencies:
          - python=3.6.3
          - pip:
            - azureml-core==1.0.72
            - azureml-dataprep[fuse,pandas]==1.3.5
            - azureml-designer-core==0.0.33          
            - torch==1.3
            - torchvision==0.4.1
    command: [python, scripts/main.py]
    args: [
      --dataset, {inputValue: Dataset type},
      --image_train_dir, {inputPath: Train data path},
      --image_test_dir, {inputPath: Evaluate data path},
      --image_size, {inputValue: Image size},
      --c_dim, {inputValue: Label dim},
      --num_iters, {inputValue: Number of iterations},
      --batch_size, {inputValue: Batch size},
      --save_dir, {outputPath: Save path},
    ]
