name: NER Train
description: NER train module
inputs:
- name: Input train data
  type: DataFrameDirectory
  description: input train data
- name: BERT pretrained model
  type: String
  default: "bert-base-cased"
  description: Specify BERT pretrained model
- name: Maximum sequence length
  type: Int
  default: 128
  description: Specify maximum sequence length
- name: Number of training epochs
  type: Int
  default: 5
  description: Specify number of training epochs
    training
- name: Warmup proportion
  type: Float
  default: 0.4
  description: Specify warmup proportion
outputs:
- name: Output model
  type: ModelDirectory
  description: The output directory where the model predictions and checkpoints will be written.
implementation:
  container:
    image: mycorp/my-docker-image
    command:
    - python
    - -m
    - script.train
    args:
    - --train-feature-dir
    - inputValue: Input train data
    - --bert-model
    - inputValue: BERT pretrained model
    - --max-seq-length
    - inputValue: Maximum sequence length
    - --num-train-epochs
    - inputValue: Number of training epochs
    - --warmup-proportion
    - inputValue: Warmup proportion
    - --output-model-dir
    - outputPath: Output model
